server:
  port: 8762

spring:
  application:
    name: gateway-router

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address : localhost